// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/paxos.proto

package paxoskv

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BallotNum is the ballot number in paxos. It consists of a monotonically
// incremental number and a universally unique ProposerId.
type BallotNum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int64                  `protobuf:"varint,1,opt,name=N,proto3" json:"N,omitempty"`
	ProposerId    int64                  `protobuf:"varint,2,opt,name=ProposerId,proto3" json:"ProposerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallotNum) Reset() {
	*x = BallotNum{}
	mi := &file_proto_paxos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallotNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallotNum) ProtoMessage() {}

func (x *BallotNum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallotNum.ProtoReflect.Descriptor instead.
func (*BallotNum) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{0}
}

func (x *BallotNum) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *BallotNum) GetProposerId() int64 {
	if x != nil {
		return x.ProposerId
	}
	return 0
}

// Value is the value part of a key-value record.
// In this demo it is just a int64
type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vi64          int64                  `protobuf:"varint,1,opt,name=Vi64,proto3" json:"Vi64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_proto_paxos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetVi64() int64 {
	if x != nil {
		return x.Vi64
	}
	return 0
}

// PaxosInstanceId specifies what paxos instance it runs on.
// A paxos instance is used to determine a specific version of a record.
// E.g.: for a key-value record foo₀=0, to set foo=2, a paxos instance is
// created to choose the value for key "foo", ver "1", i.e., foo₁
type PaxosInstanceId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the key of a record to operate on.
	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	// the version of the record to modify.
	Ver           int64 `protobuf:"varint,2,opt,name=Ver,proto3" json:"Ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaxosInstanceId) Reset() {
	*x = PaxosInstanceId{}
	mi := &file_proto_paxos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaxosInstanceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaxosInstanceId) ProtoMessage() {}

func (x *PaxosInstanceId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaxosInstanceId.ProtoReflect.Descriptor instead.
func (*PaxosInstanceId) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{2}
}

func (x *PaxosInstanceId) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PaxosInstanceId) GetVer() int64 {
	if x != nil {
		return x.Ver
	}
	return 0
}

// Acceptor is the state of an Acceptor and also serves as the reply of the
// Prepare/Accept.
type Acceptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the last ballot number the instance knows of.
	LastBal *BallotNum `protobuf:"bytes,1,opt,name=LastBal,proto3" json:"LastBal,omitempty"`
	// the voted value by this Acceptor
	Val *Value `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
	// at which ballot number the Acceptor voted it.
	VBal          *BallotNum `protobuf:"bytes,3,opt,name=VBal,proto3" json:"VBal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acceptor) Reset() {
	*x = Acceptor{}
	mi := &file_proto_paxos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acceptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acceptor) ProtoMessage() {}

func (x *Acceptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acceptor.ProtoReflect.Descriptor instead.
func (*Acceptor) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{3}
}

func (x *Acceptor) GetLastBal() *BallotNum {
	if x != nil {
		return x.LastBal
	}
	return nil
}

func (x *Acceptor) GetVal() *Value {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *Acceptor) GetVBal() *BallotNum {
	if x != nil {
		return x.VBal
	}
	return nil
}

// Proposer is the state of a Proposer and also serves as the request of
// Prepare/Accept.
type Proposer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// what paxos instance it runs on
	Id *PaxosInstanceId `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// Bal is the ballot number of a Proposer
	Bal *BallotNum `protobuf:"bytes,2,opt,name=Bal,proto3" json:"Bal,omitempty"`
	// Val is the value a Proposer has chosen.
	Val           *Value `protobuf:"bytes,3,opt,name=Val,proto3" json:"Val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proposer) Reset() {
	*x = Proposer{}
	mi := &file_proto_paxos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proposer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposer) ProtoMessage() {}

func (x *Proposer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paxos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposer.ProtoReflect.Descriptor instead.
func (*Proposer) Descriptor() ([]byte, []int) {
	return file_proto_paxos_proto_rawDescGZIP(), []int{4}
}

func (x *Proposer) GetId() *PaxosInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Proposer) GetBal() *BallotNum {
	if x != nil {
		return x.Bal
	}
	return nil
}

func (x *Proposer) GetVal() *Value {
	if x != nil {
		return x.Val
	}
	return nil
}

var File_proto_paxos_proto protoreflect.FileDescriptor

const file_proto_paxos_proto_rawDesc = "" +
	"\n" +
	"\x11proto/paxos.proto\x12\apaxoskv\"9\n" +
	"\tBallotNum\x12\f\n" +
	"\x01N\x18\x01 \x01(\x03R\x01N\x12\x1e\n" +
	"\n" +
	"ProposerId\x18\x02 \x01(\x03R\n" +
	"ProposerId\"\x1b\n" +
	"\x05Value\x12\x12\n" +
	"\x04Vi64\x18\x01 \x01(\x03R\x04Vi64\"5\n" +
	"\x0fPaxosInstanceId\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x10\n" +
	"\x03Ver\x18\x02 \x01(\x03R\x03Ver\"\x82\x01\n" +
	"\bAcceptor\x12,\n" +
	"\aLastBal\x18\x01 \x01(\v2\x12.paxoskv.BallotNumR\aLastBal\x12 \n" +
	"\x03Val\x18\x02 \x01(\v2\x0e.paxoskv.ValueR\x03Val\x12&\n" +
	"\x04VBal\x18\x03 \x01(\v2\x12.paxoskv.BallotNumR\x04VBal\"|\n" +
	"\bProposer\x12(\n" +
	"\x02Id\x18\x01 \x01(\v2\x18.paxoskv.PaxosInstanceIdR\x02Id\x12$\n" +
	"\x03Bal\x18\x02 \x01(\v2\x12.paxoskv.BallotNumR\x03Bal\x12 \n" +
	"\x03Val\x18\x03 \x01(\v2\x0e.paxoskv.ValueR\x03Val2n\n" +
	"\aPaxosKV\x121\n" +
	"\aPrepare\x12\x11.paxoskv.Proposer\x1a\x11.paxoskv.Acceptor\"\x00\x120\n" +
	"\x06Accept\x12\x11.paxoskv.Proposer\x1a\x11.paxoskv.Acceptor\"\x00B\x1dZ\x1bgithub.com/openacid/paxoskvb\x06proto3"

var (
	file_proto_paxos_proto_rawDescOnce sync.Once
	file_proto_paxos_proto_rawDescData []byte
)

func file_proto_paxos_proto_rawDescGZIP() []byte {
	file_proto_paxos_proto_rawDescOnce.Do(func() {
		file_proto_paxos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paxos_proto_rawDesc), len(file_proto_paxos_proto_rawDesc)))
	})
	return file_proto_paxos_proto_rawDescData
}

var file_proto_paxos_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_paxos_proto_goTypes = []any{
	(*BallotNum)(nil),       // 0: paxoskv.BallotNum
	(*Value)(nil),           // 1: paxoskv.Value
	(*PaxosInstanceId)(nil), // 2: paxoskv.PaxosInstanceId
	(*Acceptor)(nil),        // 3: paxoskv.Acceptor
	(*Proposer)(nil),        // 4: paxoskv.Proposer
}
var file_proto_paxos_proto_depIdxs = []int32{
	0, // 0: paxoskv.Acceptor.LastBal:type_name -> paxoskv.BallotNum
	1, // 1: paxoskv.Acceptor.Val:type_name -> paxoskv.Value
	0, // 2: paxoskv.Acceptor.VBal:type_name -> paxoskv.BallotNum
	2, // 3: paxoskv.Proposer.Id:type_name -> paxoskv.PaxosInstanceId
	0, // 4: paxoskv.Proposer.Bal:type_name -> paxoskv.BallotNum
	1, // 5: paxoskv.Proposer.Val:type_name -> paxoskv.Value
	4, // 6: paxoskv.PaxosKV.Prepare:input_type -> paxoskv.Proposer
	4, // 7: paxoskv.PaxosKV.Accept:input_type -> paxoskv.Proposer
	3, // 8: paxoskv.PaxosKV.Prepare:output_type -> paxoskv.Acceptor
	3, // 9: paxoskv.PaxosKV.Accept:output_type -> paxoskv.Acceptor
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_paxos_proto_init() }
func file_proto_paxos_proto_init() {
	if File_proto_paxos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paxos_proto_rawDesc), len(file_proto_paxos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_paxos_proto_goTypes,
		DependencyIndexes: file_proto_paxos_proto_depIdxs,
		MessageInfos:      file_proto_paxos_proto_msgTypes,
	}.Build()
	File_proto_paxos_proto = out.File
	file_proto_paxos_proto_goTypes = nil
	file_proto_paxos_proto_depIdxs = nil
}
